
ALTER TABLE `program` CHANGE `20` `20` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `program` CHANGE `20.30` `20.30` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `program` CHANGE `21` `21` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `program` CHANGE `21.30` `21.30` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `program` CHANGE `22` `22` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `program` CHANGE `22.30` `22.30` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `program` CHANGE `23` `23` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `program` CHANGE `23.30` `23.30` BOOLEAN NOT NULL DEFAULT FALSE;